### ISSUE TITLE
Show countdown between 2 columns in table

### ISSUE THREAD

**Issue by robertnicjoo** [jpmurray/laravel-countdown#7]
Hi,

How can I show time difference between 2 column?

Explain:

I have `discount_date` column in my products table and I want to show countdown between `updated_at` and `discount_date` .

How do I do that?

PS: I also get

```
Non-static method jpmurray\LaravelCountdown\Countdown::from() should not be called statically
```
when i use sample in codes in this package.

**Comment by robertnicjoo** [comment]
any help?

**Comment by jpmurray** [comment]
@robertnicjoo for the non-static method, there is a problem with the auto-loading of facades. See https://github.com/jpmurray/laravel-countdown/issues/6#issuecomment-327870323 for a quick fix.

After that, you only need to do the first example in the usage section of the readme.
